wandb_version: 1

resize_size:
  desc: null
  value: 256
crop_size:
  desc: null
  value: 224
batch_size:
  desc: null
  value: 4
num_epochs:
  desc: null
  value: 20
lr:
  desc: null
  value: 0.001
wd:
  desc: null
  value: 0.0001
step_size:
  desc: null
  value: 5
run_name:
  desc: null
  value: prova
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.17.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1721830085
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.7
      5: 0.17.5
      8:
      - 1
      - 5
      13: darwin-x86_64
